Description: Cria bucket no S3

Resources:

  BucketRenatoS3:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: bucket-renato-cursoeng
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
          - ServerSideEncryptionByDefault: 
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration: 
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Prefix: "test/test"
